# This is a basic workflow to help you get started with Actions

name: CMake Build

# Controls when the action will run. 
on: [push, pull_request]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
      
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Run CMake
        run: |
          cmake -S . -B build -G Ninja -D CMAKE_MAKE_PROGRAM=ninja
          cmake --build build -j 2
          
      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
