name: CMake Build

on: [push, pull_request]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update

      - name: Run CMake
        run: |
          cmake -S . -B build
          cmake --build build -j 2
      
      - name: Run test
        run: build/main
      
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: upload binary
          path: build/main
